import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1742320862584 implements MigrationInterface {
    name = 'Migration1742320862584'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "SECTOR" ("PK_SECTOR" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(100) NOT NULL, CONSTRAINT "PK_a58f81ac08897b248bd52a80d7c" PRIMARY KEY ("PK_SECTOR"))`);
        await queryRunner.query(`CREATE TABLE "INSTRUCTOR" ("PK_INSTRUCTOR" int NOT NULL IDENTITY(1,1), "DOC_IDENTIDAD" nvarchar(20) NOT NULL, "NOMBRE" nvarchar(50) NOT NULL, "APELLIDO" nvarchar(50) NOT NULL, "CORREO" nvarchar(100) NOT NULL, "USUARIO" nvarchar(60) NOT NULL, "ESTADO" nvarchar(50) NOT NULL, "TITULO" nvarchar(50), "NUM_CONTACTO" nvarchar(50), CONSTRAINT "UQ_b8688c108e620d4177fbe785534" UNIQUE ("DOC_IDENTIDAD"), CONSTRAINT "PK_3698a0acaae42764fa0c804606d" PRIMARY KEY ("PK_INSTRUCTOR"))`);
        await queryRunner.query(`CREATE TABLE "CURSO" ("PK_CURSO" int NOT NULL IDENTITY(1,1), "SIGLA" nvarchar(50) NOT NULL, "NOMBRE" nvarchar(100) NOT NULL, "INTENSIDAD" int NOT NULL, "ESTADO" nvarchar(50) NOT NULL, "ESTADO_MATERIAL" nvarchar(50) NOT NULL, "FECHA_LANZAMIENTO" date, "TIPO" nvarchar(50) NOT NULL, "IDIOMA" nvarchar(50), "ORGANIZACION" nvarchar(50), "ACRONIMO" nvarchar(50), "VER_MATERIAL" nvarchar(50), "VER_PLATAFORMA" nvarchar(50), "CATEGORIA" nvarchar(100), CONSTRAINT "PK_f774056a605176c2d2773009931" PRIMARY KEY ("PK_CURSO"))`);
        await queryRunner.query(`CREATE TABLE "HORARIO" ("PK_HORARIO" int NOT NULL IDENTITY(1,1), "FECHA" date NOT NULL, "HORA_INICIO" time NOT NULL, "HORA_FIN" time NOT NULL, "FK_GRUPO" int, CONSTRAINT "CK_HORA_INICIO_FIN" CHECK (HORA_FIN > HORA_INICIO), CONSTRAINT "PK_88272e1d7185e7314778f2c9967" PRIMARY KEY ("PK_HORARIO"))`);
        await queryRunner.query(`CREATE TABLE "PREGUNTA" ("PK_PREGUNTA" int NOT NULL IDENTITY(1,1), "PREGUNTA" nvarchar(MAX) NOT NULL, "CATEGORIA" nvarchar(50) NOT NULL, "TIPO" nvarchar(50) NOT NULL, "ESTADO" nvarchar(50) NOT NULL, "ORDEN" int, CONSTRAINT "CK_ESTADO_PREGUNTA" CHECK (ESTADO='Deshabilitado' OR ESTADO='Habilitado'), CONSTRAINT "PK_250660e146dd965c43983cf55c1" PRIMARY KEY ("PK_PREGUNTA"))`);
        await queryRunner.query(`CREATE TABLE "ENCUESTA" ("PK_ENCUESTA" int NOT NULL IDENTITY(1,1), "RESPUESTA" nvarchar(MAX) NOT NULL, "FECHA" date NOT NULL, "FK_PREGUNTA" int, "FK_GRUPO" int, "FK_ESTUDIANTE" int, CONSTRAINT "PK_3eded390ae73da1b6079b8b25e1" PRIMARY KEY ("PK_ENCUESTA"))`);
        await queryRunner.query(`CREATE TABLE "TIPO_GRUPO" ("PK_TIPO_GRUPO" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(50), CONSTRAINT "PK_5ee11271cac0dfb9cd1bb6e056d" PRIMARY KEY ("PK_TIPO_GRUPO"))`);
        await queryRunner.query(`CREATE TABLE "GRUPO" ("PK_GRUPO" int NOT NULL IDENTITY(1,1), "FECHA_INICIO" date NOT NULL, "FECHA_FIN" date NOT NULL, "ALCANCE" nvarchar(50), "ENTREGA_MODIFICADA" bit, "INFORME" nvarchar(MAX), "FK_CURSO" int, "FK_SALON" int, "FK_INSTRUCTOR" int, "FK_TIPO_GRUPO" int, CONSTRAINT "PK_65b120cd6eb8668fd864189049e" PRIMARY KEY ("PK_GRUPO"))`);
        await queryRunner.query(`CREATE TABLE "SALON" ("PK_SALON" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(100) NOT NULL, "LUGAR" nvarchar(80) NOT NULL, "DIRECCION" nvarchar(100), "ESTADO" nvarchar(50) NOT NULL, "CAPACIDAD" int NOT NULL, "FK_UBICACION" int, CONSTRAINT "CK_CAPACIDAD" CHECK (CAPACIDAD > 0), CONSTRAINT "CK_ESTADO_SALON" CHECK (ESTADO = 'Deshabilitado' OR ESTADO = 'Habilitado'), CONSTRAINT "PK_cbf03738dde736d797a03e4c12e" PRIMARY KEY ("PK_SALON"))`);
        await queryRunner.query(`CREATE TABLE "UBICACION" ("PK_UBICACION" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(50) NOT NULL, "FK_PAIS" int, CONSTRAINT "PK_a40380e5c20a5f60499d9efc716" PRIMARY KEY ("PK_UBICACION"))`);
        await queryRunner.query(`CREATE TABLE "PAIS" ("PK_PAIS" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(50) NOT NULL, CONSTRAINT "PK_PAIS" PRIMARY KEY ("PK_PAIS"))`);
        await queryRunner.query(`CREATE TABLE "EMPRESA" ("PK_EMPRESA" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(200) NOT NULL, "NIT" nvarchar(25), "CUSTOMER_NUMBER" int NOT NULL, "FK_SECTOR" int, "FK_PAIS" int, CONSTRAINT "PK_9d0fc2c42f4f250c853e93a1d68" PRIMARY KEY ("PK_EMPRESA"))`);
        await queryRunner.query(`CREATE TABLE "CLASE" ("PFK_ESTUDIANTE" int NOT NULL, "PFK_GRUPO" int NOT NULL, "ESTADO_ENCUESTA" nvarchar(50) NOT NULL, "ESTADO_MATERIAL" nvarchar(50) NOT NULL, "ESTADO_CERTIFICADO" nvarchar(50) NOT NULL, "ORDEN_VENTA" nvarchar(50), "CALIFICACION" numeric(5,2), "FECHA" date, "FK_EMPRESA" int, "FK_PAIS_ORDEN_VENTA" int, CONSTRAINT "PK_3c69d031ecb880e04bf721b0760" PRIMARY KEY ("PFK_ESTUDIANTE", "PFK_GRUPO"))`);
        await queryRunner.query(`CREATE TABLE "ESTUDIANTE" ("pk_estudiante" int NOT NULL IDENTITY(1,1), "doc_identidad" nvarchar(20) NOT NULL, "nombre" nvarchar(50) NOT NULL, "apellido" nvarchar(50) NOT NULL, "correo" nvarchar(100) NOT NULL, "usuario" nvarchar(60) NOT NULL, "num_contacto" nvarchar(50) NOT NULL, "registrado" bit NOT NULL CONSTRAINT "DF_3c6acf56239518ecf857c778612" DEFAULT 1, "tipo_doc" nvarchar(50) NOT NULL, "FK_PAIS" int NOT NULL, CONSTRAINT "CK_DOC_IDENTIDAD_ESTUDIANTE" CHECK (DOC_IDENTIDAD='0' OR (ISNUMERIC(DOC_IDENTIDAD)=1 AND LEN(DOC_IDENTIDAD)>=6 AND LEN(DOC_IDENTIDAD)<=12)), CONSTRAINT "CK_NUM_CONTACTO_ESTUDIANTE" CHECK (NUM_CONTACTO='0' OR LEN(NUM_CONTACTO)>=7), CONSTRAINT "PK_ESTUDIANTE" PRIMARY KEY ("pk_estudiante"))`);
        await queryRunner.query(`CREATE INDEX "IX_DOC_IDENTIDAD_ESTUDIANTE" ON "ESTUDIANTE" ("doc_identidad") `);
        await queryRunner.query(`CREATE TABLE "CERTIFICADO" ("PK_CERTIFICADO" int NOT NULL IDENTITY(1,1), "fecha" date NOT NULL, "FK_GRUPO" int NOT NULL, "FK_ESTUDIANTE" int NOT NULL, CONSTRAINT "PK_c20dd747b70f8141b6f57cc31b5" PRIMARY KEY ("PK_CERTIFICADO"))`);
        await queryRunner.query(`CREATE TABLE "ADMINISTRADOR" ("pk_administrador" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(50) NOT NULL, "apellido" nvarchar(50) NOT NULL, "correo" nvarchar(100) NOT NULL, "usuario" nvarchar(50) NOT NULL, "estado" nvarchar(50) NOT NULL CONSTRAINT "DF_00e87e7444da94819addf05dfa8" DEFAULT 'Deshabilitado', CONSTRAINT "CHK_ESTADO_ADMINISTRADOR" CHECK (estado='Habilitado' OR estado='Deshabilitado'), CONSTRAINT "PK_ADMINISTRADOR" PRIMARY KEY ("pk_administrador"))`);
        await queryRunner.query(`CREATE TABLE "ESRI_ACADEMY" ("PK_CURSO_VIRTUAL" int NOT NULL IDENTITY(1,1), "CUSTOMER_NUMBER" int, "CUSTOMER_NAME" varchar(350), "SECTOR" varchar(250), "INDUSTRY" varchar(250), "USER_FULL_NAME" varchar(300), "USER_PRIMARY_EMAIL_ADDRESS" varchar(200) NOT NULL, "CITY" varchar(100), "STATE" varchar(50), "COUNTRY_NAME" varchar(100), "LEARNING_OBJECT_TYPE" varchar(150), "LEARNING_OBJECT_TITLE" varchar(350), "START_DATE" date, "COMPLETION_DATE" date, CONSTRAINT "PK_27af2cbdb28031f6d2f0ee55d07" PRIMARY KEY ("PK_CURSO_VIRTUAL"))`);
        await queryRunner.query(`ALTER TABLE "HORARIO" ADD CONSTRAINT "FK_HORARIO_GRUPO" FOREIGN KEY ("FK_GRUPO") REFERENCES "GRUPO"("PK_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" ADD CONSTRAINT "FK_ENCUESTA_PREGUNTA" FOREIGN KEY ("FK_PREGUNTA") REFERENCES "PREGUNTA"("PK_PREGUNTA") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" ADD CONSTRAINT "FK_ENCUESTA_GRUPO" FOREIGN KEY ("FK_GRUPO") REFERENCES "GRUPO"("PK_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" ADD CONSTRAINT "FK_ENCUESTA_ESTUDIANTE" FOREIGN KEY ("FK_ESTUDIANTE") REFERENCES "ESTUDIANTE"("pk_estudiante") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_CURSO" FOREIGN KEY ("FK_CURSO") REFERENCES "CURSO"("PK_CURSO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_SALON" FOREIGN KEY ("FK_SALON") REFERENCES "SALON"("PK_SALON") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_INSTRUCTOR" FOREIGN KEY ("FK_INSTRUCTOR") REFERENCES "INSTRUCTOR"("PK_INSTRUCTOR") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_TIPO_GRUPO" FOREIGN KEY ("FK_TIPO_GRUPO") REFERENCES "TIPO_GRUPO"("PK_TIPO_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALON" ADD CONSTRAINT "FK_SALON_UBICACION" FOREIGN KEY ("FK_UBICACION") REFERENCES "UBICACION"("PK_UBICACION") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UBICACION" ADD CONSTRAINT "FK_UBICACION_PAIS" FOREIGN KEY ("FK_PAIS") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" ADD CONSTRAINT "FK_EMPRESA_SECTOR" FOREIGN KEY ("FK_SECTOR") REFERENCES "SECTOR"("PK_SECTOR") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" ADD CONSTRAINT "FK_EMPRESA_PAIS" FOREIGN KEY ("FK_PAIS") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_ESTUDIANTE" FOREIGN KEY ("PFK_ESTUDIANTE") REFERENCES "ESTUDIANTE"("pk_estudiante") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_GRUPO" FOREIGN KEY ("PFK_GRUPO") REFERENCES "GRUPO"("PK_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_EMPRESA" FOREIGN KEY ("FK_EMPRESA") REFERENCES "EMPRESA"("PK_EMPRESA") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_PAIS" FOREIGN KEY ("FK_PAIS_ORDEN_VENTA") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ESTUDIANTE" ADD CONSTRAINT "FK_f8329408e489c1d38c8fe2eaaa4" FOREIGN KEY ("FK_PAIS") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CERTIFICADO" ADD CONSTRAINT "FK_CERTIFICADO_GRUPO" FOREIGN KEY ("FK_GRUPO") REFERENCES "GRUPO"("PK_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CERTIFICADO" ADD CONSTRAINT "FK_CERTIFICADO_ESTUDIANTE" FOREIGN KEY ("FK_ESTUDIANTE") REFERENCES "ESTUDIANTE"("pk_estudiante") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "CERTIFICADO" DROP CONSTRAINT "FK_CERTIFICADO_ESTUDIANTE"`);
        await queryRunner.query(`ALTER TABLE "CERTIFICADO" DROP CONSTRAINT "FK_CERTIFICADO_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "ESTUDIANTE" DROP CONSTRAINT "FK_f8329408e489c1d38c8fe2eaaa4"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_PAIS"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_EMPRESA"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_ESTUDIANTE"`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" DROP CONSTRAINT "FK_EMPRESA_PAIS"`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" DROP CONSTRAINT "FK_EMPRESA_SECTOR"`);
        await queryRunner.query(`ALTER TABLE "UBICACION" DROP CONSTRAINT "FK_UBICACION_PAIS"`);
        await queryRunner.query(`ALTER TABLE "SALON" DROP CONSTRAINT "FK_SALON_UBICACION"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_TIPO_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_INSTRUCTOR"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_SALON"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_CURSO"`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" DROP CONSTRAINT "FK_ENCUESTA_ESTUDIANTE"`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" DROP CONSTRAINT "FK_ENCUESTA_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" DROP CONSTRAINT "FK_ENCUESTA_PREGUNTA"`);
        await queryRunner.query(`ALTER TABLE "HORARIO" DROP CONSTRAINT "FK_HORARIO_GRUPO"`);
        await queryRunner.query(`DROP TABLE "ESRI_ACADEMY"`);
        await queryRunner.query(`DROP TABLE "ADMINISTRADOR"`);
        await queryRunner.query(`DROP TABLE "CERTIFICADO"`);
        await queryRunner.query(`DROP INDEX "IX_DOC_IDENTIDAD_ESTUDIANTE" ON "ESTUDIANTE"`);
        await queryRunner.query(`DROP TABLE "ESTUDIANTE"`);
        await queryRunner.query(`DROP TABLE "CLASE"`);
        await queryRunner.query(`DROP TABLE "EMPRESA"`);
        await queryRunner.query(`DROP TABLE "PAIS"`);
        await queryRunner.query(`DROP TABLE "UBICACION"`);
        await queryRunner.query(`DROP TABLE "SALON"`);
        await queryRunner.query(`DROP TABLE "GRUPO"`);
        await queryRunner.query(`DROP TABLE "TIPO_GRUPO"`);
        await queryRunner.query(`DROP TABLE "ENCUESTA"`);
        await queryRunner.query(`DROP TABLE "PREGUNTA"`);
        await queryRunner.query(`DROP TABLE "HORARIO"`);
        await queryRunner.query(`DROP TABLE "CURSO"`);
        await queryRunner.query(`DROP TABLE "INSTRUCTOR"`);
        await queryRunner.query(`DROP TABLE "SECTOR"`);
    }

}
