import { MigrationInterface, QueryRunner } from "typeorm";

export class MigracionInicial1743199302692 implements MigrationInterface {
    name = 'MigracionInicial1743199302692'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "SECTOR" ("PK_SECTOR" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(100) NOT NULL, CONSTRAINT "PK_SECTOR" PRIMARY KEY ("PK_SECTOR"))`);
        await queryRunner.query(`CREATE TABLE "EMPRESA" ("PK_EMPRESA" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(100) NOT NULL, "NIT" nvarchar(20), "CUSTOMER_NUMBER" int, "FK_SECTOR" int, "FK_PAIS" int, CONSTRAINT "CK_NIT" CHECK ([NIT] IS NULL OR ISNUMERIC([NIT]) = 1 AND LEFT([NIT], 1) LIKE '[1-9]'), CONSTRAINT "PK_EMPRESA" PRIMARY KEY ("PK_EMPRESA"))`);
        await queryRunner.query(`CREATE INDEX "IXFK_EMPRESA_SECTOR" ON "EMPRESA" ("FK_SECTOR") `);
        await queryRunner.query(`CREATE TABLE "INSTRUCTOR" ("PK_INSTRUCTOR" int NOT NULL IDENTITY(1,1), "DOC_IDENTIDAD" nvarchar(20) NOT NULL, "NOMBRE" nvarchar(50) NOT NULL, "APELLIDO" nvarchar(50) NOT NULL, "CORREO" nvarchar(100) NOT NULL, "USUARIO" nvarchar(60) NOT NULL, "ESTADO" nvarchar(50) NOT NULL, "TITULO" nvarchar(50), "NUM_CONTACTO" nvarchar(50), CONSTRAINT "CK_TITULO" CHECK ([TITULO] IS NULL OR [TITULO] IN ('Ing.', 'Esp.', 'Lic.', 'MSc.', 'PhD.', 'Dr.', 'Arq.')), CONSTRAINT "CK_NUM_CONTACTO_INSTRUCTOR" CHECK ([NUM_CONTACTO] IS NULL OR LEN([NUM_CONTACTO])>=7), CONSTRAINT "CK_ESTADO_INSTRUCTOR" CHECK ([ESTADO]='Deshabilitado' OR [ESTADO]='Habilitado'), CONSTRAINT "CK_DOC_IDENTIDAD_INSTRUCTOR" CHECK ([DOC_IDENTIDAD]='0' OR ISNUMERIC([DOC_IDENTIDAD])=1 AND LEN([DOC_IDENTIDAD])>=6 AND LEN([DOC_IDENTIDAD])<=12), CONSTRAINT "PK_INSTRUCTOR" PRIMARY KEY ("PK_INSTRUCTOR"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IXAK_DOC_IDENTIDAD_INSTRUCTOR" ON "INSTRUCTOR" ("DOC_IDENTIDAD") `);
        await queryRunner.query(`CREATE TABLE "CURSO" ("PK_CURSO" int NOT NULL IDENTITY(1,1), "SIGLA" nvarchar(50) NOT NULL, "NOMBRE" nvarchar(100) NOT NULL, "INTENSIDAD" int NOT NULL, "ESTADO" nvarchar(50) NOT NULL, "ESTADO_MATERIAL" nvarchar(50) NOT NULL, "FECHA_LANZAMIENTO" date, "TIPO" nvarchar(50), "IDIOMA" nvarchar(50), "ORGANIZACION" nvarchar(50), "ACRONIMO" nvarchar(50), "VER_MATERIAL" nvarchar(50), "VER_PLATAFORMA" nvarchar(50), "CATEGORIA" nvarchar(100), CONSTRAINT "CK_ORGANIZACION" CHECK ([ORGANIZACION]='Esri Colombia' OR [ORGANIZACION]='Esri Panamá' OR [ORGANIZACION]='Esri Ecuador' OR [ORGANIZACION]='Esri Chile' OR [ORGANIZACION]='Esri Inc'), CONSTRAINT "CK_INTENSIDAD" CHECK ([INTENSIDAD] > 0), CONSTRAINT "CK_IDIOMA" CHECK ([IDIOMA] = 'Inglés' OR [IDIOMA] = 'Español'), CONSTRAINT "CK_ESTADO_MATERIAL_CURSO" CHECK ([ESTADO_MATERIAL] = 'Deshabilitado' OR [ESTADO_MATERIAL] = 'Habilitado'), CONSTRAINT "CK_ESTADO_CURSO" CHECK ([ESTADO] = 'Deshabilitado' OR [ESTADO] = 'Habilitado'), CONSTRAINT "PK_CURSO" PRIMARY KEY ("PK_CURSO"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IXAK_SIGLA" ON "CURSO" ("SIGLA") `);
        await queryRunner.query(`CREATE TABLE "HORARIO" ("PK_HORARIO" int NOT NULL IDENTITY(1,1), "FECHA" date NOT NULL, "HORA_INICIO" time NOT NULL, "HORA_FIN" time NOT NULL, "FK_GRUPO" int NOT NULL, CONSTRAINT "CK_HORA_INICIO_FIN" CHECK (HORA_FIN > HORA_INICIO), CONSTRAINT "PK_HORARIO" PRIMARY KEY ("PK_HORARIO"))`);
        await queryRunner.query(`CREATE INDEX "IXFK_HORARIO_GRUPO" ON "HORARIO" ("FK_GRUPO") `);
        await queryRunner.query(`CREATE TABLE "TIPO_GRUPO" ("PK_TIPO_GRUPO" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(50), CONSTRAINT "PK_TIPO_GRUPO" PRIMARY KEY ("PK_TIPO_GRUPO"))`);
        await queryRunner.query(`CREATE TABLE "GRUPO" ("PK_GRUPO" int NOT NULL IDENTITY(1,1), "FECHA_INICIO" date NOT NULL, "FECHA_FIN" date NOT NULL, "ALCANCE" nvarchar(50), "ENTREGA_MODIFICADA" bit, "INFORME" nvarchar(MAX), "FK_INSTRUCTOR" int, "FK_SALON" int, "FK_CURSO" int NOT NULL, "FK_TIPO_GRUPO" int, CONSTRAINT "CK_FECHA_INICIO_FIN" CHECK ([FECHA_FIN] >= [FECHA_INICIO]), CONSTRAINT "CK_ALCANCE" CHECK ([ALCANCE] = 'Abierto' OR [ALCANCE] = 'Privado'), CONSTRAINT "PK_GRUPO" PRIMARY KEY ("PK_GRUPO"))`);
        await queryRunner.query(`CREATE INDEX "IXFK_GRUPO_SALON" ON "GRUPO" ("FK_SALON") `);
        await queryRunner.query(`CREATE INDEX "IXFK_GRUPO_INSTRUCTOR" ON "GRUPO" ("FK_INSTRUCTOR") `);
        await queryRunner.query(`CREATE INDEX "IXFK_GRUPO_CURSO" ON "GRUPO" ("FK_CURSO") `);
        await queryRunner.query(`CREATE TABLE "SALON" ("PK_SALON" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(100) NOT NULL, "LUGAR" nvarchar(80) NOT NULL, "DIRECCION" nvarchar(100), "ESTADO" nvarchar(50) NOT NULL, "CAPACIDAD" int NOT NULL, "FK_UBICACION" int NOT NULL, CONSTRAINT "CK_CAPACIDAD" CHECK (CAPACIDAD > 0), CONSTRAINT "CK_ESTADO_SALON" CHECK (ESTADO = 'Deshabilitado' OR ESTADO = 'Habilitado'), CONSTRAINT "PK_SALON" PRIMARY KEY ("PK_SALON"))`);
        await queryRunner.query(`CREATE INDEX "IXFK_SALON_UBICACION" ON "SALON" ("FK_UBICACION") `);
        await queryRunner.query(`CREATE TABLE "UBICACION" ("PK_UBICACION" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(50) NOT NULL, "FK_PAIS" int, CONSTRAINT "PK_UBICACION" PRIMARY KEY ("PK_UBICACION"))`);
        await queryRunner.query(`CREATE TABLE "PAIS" ("PK_PAIS" int NOT NULL IDENTITY(1,1), "nombre" nvarchar(50) NOT NULL, CONSTRAINT "PK_PAIS" PRIMARY KEY ("PK_PAIS"))`);
        await queryRunner.query(`CREATE TABLE "ESTUDIANTE" ("PK_ESTUDIANTE" int NOT NULL IDENTITY(1,1), "DOC_IDENTIDAD" nvarchar(20) NOT NULL, "NOMBRE" nvarchar(50) NOT NULL, "APELLIDO" nvarchar(50) NOT NULL, "CORREO" nvarchar(100) NOT NULL, "USUARIO" nvarchar(60) NOT NULL, "NUM_CONTACTO" nvarchar(50), "REGISTRADO" bit NOT NULL CONSTRAINT "DF_a84ddc6b265eeb7860ab842a4b9" DEFAULT 1, "TIPO_DOC" nvarchar(50), "FK_PAIS" int, CONSTRAINT "CK_DOC_IDENTIDAD_ESTUDIANTE" CHECK ([DOC_IDENTIDAD]='0' OR len([DOC_IDENTIDAD])>=(6) AND len([DOC_IDENTIDAD])<=(15)), CONSTRAINT "CK_NUM_CONTACTO_ESTUDIANTE" CHECK ([NUM_CONTACTO] IS NULL OR len([NUM_CONTACTO])>=(7)), CONSTRAINT "PK_ESTUDIANTE" PRIMARY KEY ("PK_ESTUDIANTE"))`);
        await queryRunner.query(`CREATE INDEX "IX_DOC_IDENTIDAD_ESTUDIANTE" ON "ESTUDIANTE" ("DOC_IDENTIDAD") `);
        await queryRunner.query(`CREATE TABLE "CLASE" ("PFK_GRUPO" int NOT NULL, "PFK_ESTUDIANTE" int NOT NULL, "FK_EMPRESA" int, "ESTADO_ENCUESTA" nvarchar(50) NOT NULL, "ESTADO_MATERIAL" nvarchar(50) NOT NULL, "ESTADO_CERTIFICADO" nvarchar(50) NOT NULL, "ORDEN_VENTA" nvarchar(50), "CALIFICACION" numeric(5,2), "FECHA" date, "FK_PAIS_ORDEN_VENTA" int, CONSTRAINT "CK_ESTADO_MATERIAL" CHECK ([ESTADO_MATERIAL] = 'Deshabilitado' OR [ESTADO_MATERIAL] = 'Habilitado'), CONSTRAINT "CK_ESTADO_ENCUESTA" CHECK ([ESTADO_ENCUESTA] = 'Deshabilitado' OR [ESTADO_ENCUESTA] = 'Habilitado'), CONSTRAINT "CK_ESTADO_CERTIFICADO" CHECK ([ESTADO_CERTIFICADO] = 'Deshabilitado' OR [ESTADO_CERTIFICADO] = 'Habilitado'), CONSTRAINT "CK_CALIFICACION" CHECK ([CALIFICACION] >= 0 AND [CALIFICACION] <= 100), CONSTRAINT "PK_CLASE" PRIMARY KEY ("PFK_GRUPO", "PFK_ESTUDIANTE"))`);
        await queryRunner.query(`CREATE INDEX "IXFK_CLASE_GRUPO" ON "CLASE" ("PFK_GRUPO") `);
        await queryRunner.query(`CREATE INDEX "IXFK_CLASE_ESTUDIANTE" ON "CLASE" ("PFK_ESTUDIANTE") `);
        await queryRunner.query(`CREATE INDEX "IXFK_CLASE_EMPRESA" ON "CLASE" ("FK_EMPRESA") `);
        await queryRunner.query(`CREATE TABLE "CERTIFICADO" ("PK_CERTIFICADO" int NOT NULL IDENTITY(1,1), "FK_ESTUDIANTE" int NOT NULL, "FK_GRUPO" int NOT NULL, "FECHA" date NOT NULL, CONSTRAINT "PK_CERTIFICADO" PRIMARY KEY ("PK_CERTIFICADO"))`);
        await queryRunner.query(`CREATE INDEX "IXFK_CERTIFICADO_CLASE" ON "CERTIFICADO" ("FK_GRUPO", "FK_ESTUDIANTE") `);
        await queryRunner.query(`CREATE TABLE "ADMINISTRADOR" ("pk_administrador" int NOT NULL IDENTITY(1,1), "NOMBRE" nvarchar(50) NOT NULL, "APELLIDO" nvarchar(50) NOT NULL, "CORREO" nvarchar(100) NOT NULL, "USUARIO" nvarchar(50) NOT NULL, "ESTADO" nvarchar(50) NOT NULL CONSTRAINT "DF_a7c63430ce4a05f32df1c2f2d50" DEFAULT 'Deshabilitado', CONSTRAINT "CK_ESTADO_ADMINISTRADOR" CHECK (ESTADO = 'Habilitado' OR ESTADO = 'Deshabilitado'), CONSTRAINT "PK_ADMINISTRADOR" PRIMARY KEY ("pk_administrador"))`);
        await queryRunner.query(`CREATE TABLE "ESRI_ACADEMY" ("PK_CURSO_VIRTUAL" int NOT NULL IDENTITY(1,1), "CUSTOMER_NUMBER" int, "CUSTOMER_NAME" varchar(350), "SECTOR" varchar(250), "INDUSTRY" varchar(250), "USER_FULL_NAME" varchar(300), "USER_PRIMARY_EMAIL_ADDRESS" varchar(200) NOT NULL, "CITY" varchar(100), "STATE" varchar(50), "COUNTRY_NAME" varchar(100), "LEARNING_OBJECT_TYPE" varchar(150), "LEARNING_OBJECT_TITLE" varchar(350), "START_DATE" date, "COMPLETION_DATE" date, CONSTRAINT "PK_CURSO_VIRTUAL" PRIMARY KEY ("PK_CURSO_VIRTUAL"))`);
        await queryRunner.query(`CREATE TABLE "PREGUNTA" ("PK_PREGUNTA" int NOT NULL IDENTITY(1,1), "PREGUNTA" nvarchar(MAX) NOT NULL, "CATEGORIA" nvarchar(50) NOT NULL, "TIPO" nvarchar(50) NOT NULL, "ESTADO" nvarchar(50) NOT NULL, "ORDEN" int, CONSTRAINT "CK_ORDEN_PREGUNTA" CHECK ([ORDEN] > 0), CONSTRAINT "CK_CATEGORIA" CHECK (CATEGORIA IN ('Instructor', 'Material', 'Entrenamiento general', 'Salon')), CONSTRAINT "CK_ESTADO_PREGUNTA" CHECK (ESTADO='Deshabilitado' OR ESTADO='Habilitado'), CONSTRAINT "PK_PREGUNTA" PRIMARY KEY ("PK_PREGUNTA"))`);
        await queryRunner.query(`CREATE TABLE "ENCUESTA" ("PK_ENCUESTA" int NOT NULL IDENTITY(1,1), "RESPUESTA" nvarchar(MAX) NOT NULL, "FECHA" date NOT NULL, "FK_ESTUDIANTE" int NOT NULL, "FK_GRUPO" int NOT NULL, "FK_PREGUNTA" int NOT NULL, CONSTRAINT "PK_ENCUESTA" PRIMARY KEY ("PK_ENCUESTA"))`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" ADD CONSTRAINT "FK_EMPRESA_SECTOR" FOREIGN KEY ("FK_SECTOR") REFERENCES "SECTOR"("PK_SECTOR") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" ADD CONSTRAINT "FK_EMPRESA_PAIS" FOREIGN KEY ("FK_PAIS") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "HORARIO" ADD CONSTRAINT "FK_HORARIO_GRUPO" FOREIGN KEY ("FK_GRUPO") REFERENCES "GRUPO"("PK_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_CURSO" FOREIGN KEY ("FK_CURSO") REFERENCES "CURSO"("PK_CURSO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_SALON" FOREIGN KEY ("FK_SALON") REFERENCES "SALON"("PK_SALON") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_INSTRUCTOR" FOREIGN KEY ("FK_INSTRUCTOR") REFERENCES "INSTRUCTOR"("PK_INSTRUCTOR") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "GRUPO" ADD CONSTRAINT "FK_GRUPO_TIPO_GRUPO" FOREIGN KEY ("FK_TIPO_GRUPO") REFERENCES "TIPO_GRUPO"("PK_TIPO_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SALON" ADD CONSTRAINT "FK_SALON_UBICACION" FOREIGN KEY ("FK_UBICACION") REFERENCES "UBICACION"("PK_UBICACION") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UBICACION" ADD CONSTRAINT "FK_UBICACION_PAIS" FOREIGN KEY ("FK_PAIS") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ESTUDIANTE" ADD CONSTRAINT "FK_ESTUDIANTE_PAIS" FOREIGN KEY ("FK_PAIS") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_EMPRESA" FOREIGN KEY ("FK_EMPRESA") REFERENCES "EMPRESA"("PK_EMPRESA") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_PAIS" FOREIGN KEY ("FK_PAIS_ORDEN_VENTA") REFERENCES "PAIS"("PK_PAIS") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_ESTUDIANTE" FOREIGN KEY ("PFK_ESTUDIANTE") REFERENCES "ESTUDIANTE"("PK_ESTUDIANTE") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CLASE" ADD CONSTRAINT "FK_CLASE_GRUPO" FOREIGN KEY ("PFK_GRUPO") REFERENCES "GRUPO"("PK_GRUPO") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CERTIFICADO" ADD CONSTRAINT "FK_ENCUESTA_CLASE" FOREIGN KEY ("FK_GRUPO", "FK_ESTUDIANTE") REFERENCES "CLASE"("PFK_GRUPO","PFK_ESTUDIANTE") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" ADD CONSTRAINT "FK_ENCUESTA_PREGUNTA" FOREIGN KEY ("FK_PREGUNTA") REFERENCES "PREGUNTA"("PK_PREGUNTA") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" ADD CONSTRAINT "FK_ENCUESTA_CLASE" FOREIGN KEY ("FK_ESTUDIANTE", "FK_GRUPO") REFERENCES "CLASE"("PFK_ESTUDIANTE","PFK_GRUPO") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ENCUESTA" DROP CONSTRAINT "FK_ENCUESTA_CLASE"`);
        await queryRunner.query(`ALTER TABLE "ENCUESTA" DROP CONSTRAINT "FK_ENCUESTA_PREGUNTA"`);
        await queryRunner.query(`ALTER TABLE "CERTIFICADO" DROP CONSTRAINT "FK_ENCUESTA_CLASE"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_ESTUDIANTE"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_PAIS"`);
        await queryRunner.query(`ALTER TABLE "CLASE" DROP CONSTRAINT "FK_CLASE_EMPRESA"`);
        await queryRunner.query(`ALTER TABLE "ESTUDIANTE" DROP CONSTRAINT "FK_ESTUDIANTE_PAIS"`);
        await queryRunner.query(`ALTER TABLE "UBICACION" DROP CONSTRAINT "FK_UBICACION_PAIS"`);
        await queryRunner.query(`ALTER TABLE "SALON" DROP CONSTRAINT "FK_SALON_UBICACION"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_TIPO_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_INSTRUCTOR"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_SALON"`);
        await queryRunner.query(`ALTER TABLE "GRUPO" DROP CONSTRAINT "FK_GRUPO_CURSO"`);
        await queryRunner.query(`ALTER TABLE "HORARIO" DROP CONSTRAINT "FK_HORARIO_GRUPO"`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" DROP CONSTRAINT "FK_EMPRESA_PAIS"`);
        await queryRunner.query(`ALTER TABLE "EMPRESA" DROP CONSTRAINT "FK_EMPRESA_SECTOR"`);
        await queryRunner.query(`DROP TABLE "ENCUESTA"`);
        await queryRunner.query(`DROP TABLE "PREGUNTA"`);
        await queryRunner.query(`DROP TABLE "ESRI_ACADEMY"`);
        await queryRunner.query(`DROP TABLE "ADMINISTRADOR"`);
        await queryRunner.query(`DROP INDEX "IXFK_CERTIFICADO_CLASE" ON "CERTIFICADO"`);
        await queryRunner.query(`DROP TABLE "CERTIFICADO"`);
        await queryRunner.query(`DROP INDEX "IXFK_CLASE_EMPRESA" ON "CLASE"`);
        await queryRunner.query(`DROP INDEX "IXFK_CLASE_ESTUDIANTE" ON "CLASE"`);
        await queryRunner.query(`DROP INDEX "IXFK_CLASE_GRUPO" ON "CLASE"`);
        await queryRunner.query(`DROP TABLE "CLASE"`);
        await queryRunner.query(`DROP INDEX "IX_DOC_IDENTIDAD_ESTUDIANTE" ON "ESTUDIANTE"`);
        await queryRunner.query(`DROP TABLE "ESTUDIANTE"`);
        await queryRunner.query(`DROP TABLE "PAIS"`);
        await queryRunner.query(`DROP TABLE "UBICACION"`);
        await queryRunner.query(`DROP INDEX "IXFK_SALON_UBICACION" ON "SALON"`);
        await queryRunner.query(`DROP TABLE "SALON"`);
        await queryRunner.query(`DROP INDEX "IXFK_GRUPO_CURSO" ON "GRUPO"`);
        await queryRunner.query(`DROP INDEX "IXFK_GRUPO_INSTRUCTOR" ON "GRUPO"`);
        await queryRunner.query(`DROP INDEX "IXFK_GRUPO_SALON" ON "GRUPO"`);
        await queryRunner.query(`DROP TABLE "GRUPO"`);
        await queryRunner.query(`DROP TABLE "TIPO_GRUPO"`);
        await queryRunner.query(`DROP INDEX "IXFK_HORARIO_GRUPO" ON "HORARIO"`);
        await queryRunner.query(`DROP TABLE "HORARIO"`);
        await queryRunner.query(`DROP INDEX "IXAK_SIGLA" ON "CURSO"`);
        await queryRunner.query(`DROP TABLE "CURSO"`);
        await queryRunner.query(`DROP INDEX "IXAK_DOC_IDENTIDAD_INSTRUCTOR" ON "INSTRUCTOR"`);
        await queryRunner.query(`DROP TABLE "INSTRUCTOR"`);
        await queryRunner.query(`DROP INDEX "IXFK_EMPRESA_SECTOR" ON "EMPRESA"`);
        await queryRunner.query(`DROP TABLE "EMPRESA"`);
        await queryRunner.query(`DROP TABLE "SECTOR"`);
    }

}
